global proc testDllCreateUI()
{
    global string $yafarayMenu;
    if(`menu -exists $yafarayMenu`) {deleteUI $yafarayMenu;}

    global string $gMainWindow;
    global string $mainMenuName = "YafaRay";
    $yafarayMenu = `menu -parent $gMainWindow -tearOff true -label $mainMenuName`;

    //menuItem -parent $yafarayMenu -divider true testDllDividerItem1;
    menuItem -parent $yafarayMenu -label "Load Plug-in" -command "testDll" -annotation "load plugin" testDllMenuItem1;
    //menuItem -parent $yafarayMenu -divider true testDllDividerItem2;
    //don't need to be option box item....
    menuItem -parent $yafarayMenu -label "YafaRay Settings" -command "testYafaraySettingUI" -annotation "setting for Yafaray" testDllMenuItem2;
    //menuItem -parent $yafarayMenu -divider true testDllDividerItem3;
    menuItem -parent $yafarayMenu -label "Render View"  -annotation "render current view" testDllMenuItem3;
    //menuItem -parent $yafarayMenu -divider true testDllDividerItem4;
    menuItem -parent $yafarayMenu -label "Render" -annotation "render the setted camera" testDllMenuItem4;

}



global proc testDllDeleteUI()
{
    global string $yafarayMenu;
    deleteUI -menu $yafarayMenu;


}
