#define NOMINMAX
#define _USE_MATH_DEFINES 1
#ifndef WOODTEX
#define WOODTEX

#include <maya/MPxNode.h>
#include <maya/MFnNumericAttribute.h>
#include <maya/MTypeId.h> 

class woodTexNode: public MPxNode
{
public:
	virtual MStatus compute(const MPlug &plug,MDataBlock &data);
	static void * creator();
	static MStatus initialize();
	static const MTypeId id;

private:
	//shape and depth can be generated by existing parameters, no need to set them in the menu
	static MObject woodTurbulence;
	static MObject woodSize;
	static MObject woodHard;
	static MObject woodType;
	static MObject NoiseType;
	static MObject mappingMethod;
	static MObject texCo;
	static MObject UV;
	static MObject UVFilterSize;
	static MObject Output;

};
#endif